blog/urls.py
from django.urls import path
from .views import AllArticleListView, SingleArticleView, CategoryArticleListView

app_name = 'blog'
urlpatterns = [
    path('', AllArticleListView.as_view(), name='article_list'),
    path('c/<slug:slug>/', CategoryArticleListView.as_view(), name='category_article_list'),
    path('article/<slug:slug>/', SingleArticleView.as_view(), name='article_detail'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.CartDetailView.as_view() , name='cart_detail'),
    path('add/<int:product_id>', views.cart_product_add, name='card_add'),
    path('addtocart/<int:product_id>', views.add_to_cart, name='card_to_add'),
    path('remove/<int:product_id>', views.cart_product_remove, name='card_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from rest_framework_simplejwt import views as jwt_views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Shop API",
      default_version='v1',
      description="All endpoints of this shop",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="support@shop.com"),
      license=openapi.License(name="GPLv3 License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    #all project apps urls
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('', include('shop.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog')),
    #all api urls
    path('api-auth/', include('rest_framework.urls')),
    path('api/rest-auth/', include('dj_rest_auth.urls')),
    path('api/products/', include('shop_api.urls')),
    path('api/accounts/', include('accounts_api.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='create'),
    path('payment/<int:order_id>/', views.order_detail, name='detail'),
    path('request/<int:order_id>/<price>', views.send_request, name='request'),
    path('verify/', views.verify , name='verify'),
]

shop/urls.py
from django.urls import path
from . import views
from . import context_processors


app_name = 'shop'
urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('p/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('search/', views.SearchProductListView.as_view(), name='product_search'),
    path('c/<slug:slug>/', views.CategoryProductListView.as_view(), name='category_product_list'),
    path('c/<slug:slug>/lowprice-products/', views.LowPriceProductsView.as_view(), name='lowprice'),
    path('c/<slug:slug>/highprice-products/', views.HighPriceProductsView.as_view(), name='highprice'),
    path('c/<slug:slug>/a-to-z-products/', views.AZNameProductsView.as_view(), name='a-to-z-name'),
    path('c/<slug:slug>/z-to-a-products/', views.ZANameProductsView.as_view(), name='z-to-a-name'),
    path('about-us', views.AboutUsView.as_view(), name='about-us'),
    path('contact-us', views.ContactUsView.as_view(), name='contact-us'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms



class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder':'0'}))

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView
from .sessions import Cart
from shop.models import Product
from .forms import CartAddForm
from django.views.decorators.http import require_POST


class CartDetailView(TemplateView):
    template_name = 'cart/cart.html'

@require_POST
def cart_product_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add_cart(product=product, quantity=cd['quantity'])
    return redirect('cart:cart_detail')

def add_to_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add_cart(product=product, quantity=1)
    return redirect('cart:cart_detail')

def cart_product_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove_cart(product)
    return redirect('cart:cart_detail')



    

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}| Cart{% endblock title %}

{% block page_title %}Cart{% endblock page_title %}
{% block breadcrumbs %}
<li>Cart</li>
{% endblock %}
{% block content %}
<div class="shopping-cart section">
    <div class="container">
    {% if item_count > 0 %}
        <div class="cart-list-head">
            <div class="cart-list-title">
            
                <div class="row">
                    <div class="col-lg-1 col-md-1 col-12">
                    </div>
                    <div class="col-lg-4 col-md-3 col-12">
                        <p>Product Name</p>
                    </div>
                    <div class="col-lg-2 col-md-2 col-12">
                        <p>Quantity</p>
                    </div>
                    <div class="col-lg-2 col-md-2 col-12">
                        <p>Subtotal</p>
                    </div>
                    <div class="col-lg-2 col-md-2 col-12">
                        <p>Discount</p>
                    </div>
                    <div class="col-lg-1 col-md-2 col-12">
                        <p>Remove</p>
                    </div>
                </div>
            </div>
            

            {% for item in cart %}
            <div class="cart-single-list">
                <div class="row align-items-center">
                    <div class="col-lg-1 col-md-1 col-12">
                        <a href="{% url 'shop:product_detail' item.product.slug %}"><img src="{{item.product.image.url}}" alt="#"></a>
                    </div>
                    <div class="col-lg-4 col-md-3 col-12">
                        <h5 class="product-name"><a href="{% url 'shop:product_detail' item.product.slug %}">{{item.product.name}}</a></h5>
                        <p class="product-des">
                            <span><em>Type:</em> Laser</span>
                            <span><em>Color:</em> White</span>
                        </p>
                    </div>
                    <div class="col-lg-2 col-md-2 col-12">
                        <div class="count-input">
                        {{item.quantity}}
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-12">
                        <p>${{item.total_price|intcomma}}</p>
                    </div>
                    <div class="col-lg-2 col-md-2 col-12">
                    {% if item.product.discount %}
                    <p>{{item.product.discount}}%</p>
                    {% else %}
                    <p>--</p>
                    {% endif %}
                        
                    </div>
                    <div class="col-lg-1 col-md-2 col-12">
                        <a class="remove-item" href="{% url 'cart:card_remove' item.product.id %}"><i class="lni lni-close"></i></a>
                    </div>
                </div>
            </div>
                {% endfor %}
        </div>
        <div class="row">
            <div class="col-12">

                <div class="total-amount">
                    <div class="row">
                        <div class="col-lg-8 col-md-6 col-12">
                            <div class="left">
                                <div class="coupon">
                                    <form action="#" target="_blank">
                                        <input name="Coupon" placeholder="Enter Your Coupon">
                                        <div class="button">
                                            <button class="btn">Apply Coupon</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="right">
                                <ul>
                                    <li>Cart Subtotal<span>${{cart.get_total_price}}</span></li>
                                    <li>Shipping<span>Free</span></li>
                                    <li>You Save<span>$29.00</span></li>
                                    <li class="last">You Pay<span>2531T</span></li>
                                </ul>
                                <div class="button">
                                    <a href="{% url 'orders:create' %}" class="btn">Checkout</a>
                                    <a href="product-grids.html" class="btn btn-alt">Continue shopping</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        {% else %}
            <div class="cart-list-title">
            <p>You have not yet selected a product to purchase</p>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}