accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    # user dashboard urls
    path('personal-info/', views.PersonalInfoView.as_view(), name='user_personal_info'),
    path('personal-info/<int:pk>/edit/', views.PersonalInfoEditView.as_view(), name='user_personal_info_edit'),
    path('wishlist/', views.WishListView.as_view(), name='user_wish_list'),
    path('products-purchased/', views.ProductsPurchasedView.as_view(), name='products_purchased'),
    path('api-info/', views.ApiView.as_view(), name='api_info'),
    # register login and logout urls
    path('login/', views.UserLoginView, name='user_login'),
    path('login/with-password/', views.user_login_pw, name='user_login_with'),
    path('login/with-code/', views.user_login_code, name='user_login_code'),
    path('login/with-code/verify/', views.login_verify_code, name='login_verify_code'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.user_register, name='user_register'),
    path('register/verify/', views.register_verify_phone, name='register_verify_phone'),    
]

blog/urls.py
from django.urls import path
from .views import AllArticleListView, SingleArticleView, CategoryArticleListView

app_name = 'blog'
urlpatterns = [
    path('', AllArticleListView.as_view(), name='article_list'),
    path('c/<slug:slug>/', CategoryArticleListView.as_view(), name='category_article_list'),
    path('article/<slug:slug>/', SingleArticleView.as_view(), name='article_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from rest_framework_simplejwt import views as jwt_views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Shop API",
      default_version='v1',
      description="All endpoints of this shop",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="support@shop.com"),
      license=openapi.License(name="GPLv3 License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    #all project apps urls
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('', include('shop.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog')),
    #all api urls
    path('api-auth/', include('rest_framework.urls')),
    path('api/rest-auth/', include('dj_rest_auth.urls')),
    path('api/products/', include('shop_api.urls')),
    path('api/accounts/', include('accounts_api.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

shop/urls.py
from django.urls import path
from . import views
from . import context_processors


app_name = 'shop'
urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('p/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('search/', views.SearchProductListView.as_view(), name='product_search'),
    path('c/<slug:slug>/', views.CategoryProductListView.as_view(), name='category_product_list'),
    path('c/<slug:slug>/lowprice-products/', views.LowPriceProductsView.as_view(), name='lowprice'),
    path('c/<slug:slug>/highprice-products/', views.HighPriceProductsView.as_view(), name='highprice'),
    path('c/<slug:slug>/a-to-z-products/', views.AZNameProductsView.as_view(), name='a-to-z-name'),
    path('c/<slug:slug>/z-to-a-products/', views.ZANameProductsView.as_view(), name='z-to-a-name'),
    path('about-us', views.AboutUsView.as_view(), name='about-us'),
    path('contact-us', views.ContactUsView.as_view(), name='contact-us'),
]

wishlist/urls.py
from django.urls import path
from .views import WishListView, RemoveWishListView, AddWishListView


app_name = 'wishlist'
urlpatterns = [
    path('', WishListView.as_view(), name='wishlist'),
    path('add/<int:id>/<slug:slug>/', AddWishListView.as_view(), name='add_wishlist'),
    path('remove/<int:id>/', RemoveWishListView.as_view(), name='remove_wishlist'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.core.validators import RegexValidator
from .managers import UserManager



def get_user_image_folder(instance, filename):
    return "%s/%s" %(instance.phone, filename)


class User(AbstractBaseUser):
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '9XX XXX XXXX'. Up to 15 digits allowed.")
    phone = models.CharField(max_length=17, validators=[phone_regex], unique=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    nickname = models.CharField(max_length=100, null=True, blank=True, unique=True)
    bio = models.TextField(null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField(upload_to=get_user_image_folder, null=True, blank=True)
    
    is_verify = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()
    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['nickname',]

    def __str__(self):
        return self.phone
    
    def has_perm(self, perm, obj=None):
        return True
    
    def has_module_perms(self, app_label):
        return True

accounts/forms.py
from django import forms
from .models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
    phone = forms.CharField(label='Phone Number ', widget=forms.NumberInput(attrs={'class': 'form-control mb-1'}))
    nickname = forms.CharField(label='Nickname ', widget=forms.TextInput(attrs={'class': 'form-control mb-1'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ('phone','nickname')
    
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('phone','email','nickname','first_name','last_name')
    
    def clean_password(self):
        return self.initial['password']

class LoginWithPwForm(forms.Form):
    phone = forms.CharField(label='Phone', widget=forms.NumberInput(attrs={'class':'form-control mb-1'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))

    def phone_clean(self):
        phone = User.objects.filter(phone = self.cleaned_data['phone'])
        if not phone.exists():
            raise forms.ValidationError('This phone number does not exists, please enter currect phone number')
            return self.cleaned_data['phone']


class LoginWithCodeForm(forms.Form):
    phone = forms.CharField(label='Phone', widget=forms.NumberInput(attrs={'class':'form-control mb-1'}))

    def phone_clean(self):
        phone = User.objects.filter(phone = self.cleaned_data['phone'])
        if not phone.exists():
            raise forms.ValidationError('This phone number does not exists, please enter currect phone number')
            return self.cleaned_data['phone']

class VerifyCodeForm(forms.Form):
    code = forms.CharField(label='Enter code to verify', widget=forms.TextInput(attrs={'class':'form-control'}))

accounts/views.py
from django.views.generic import DetailView, TemplateView, ListView, FormView, CreateView, UpdateView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.contrib import messages
from orders.models import Order, OrderItem
from wishlist.models import WishList
from random import randint
from django import forms
from .forms import *


class PersonalInfoView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/dashboard_personal_info.html'
    context_object_name = 'user'
    
    def post(self,reqeust, **kwargs):
        user = request.user
        context = {'user':user}
        return render(request, 'accounts/personal_info.html', context)

class PersonalInfoEditView(UpdateView):
    template_name = 'accounts/dashboard_personal_info_edit.html'
    model = User
    fields = ['image','email','nickname', 'first_name', 'last_name', 'bio']
    success_url = reverse_lazy('accounts:user_personal_info')

    def form_valid(self, form):
        data = self.request.POST
        image_data = self.request.FILES
        if image_data:
            image = image_data['image']
        email = data.get('email')
        nickname = data.get('nickname')
        first_name = data.get('first_name')
        last_name = data.get('last_name')
        bio = data.get('bio')
        messages.success(self.request, "personal info updated", 'success')
        return super().form_valid(form)


class WishListView(LoginRequiredMixin, ListView):
    template_name = 'accounts/dashboard_wishlist.html'
    context_object_name = 'wishlists'

    def get_queryset(self):
        user = self.request.user
        return WishList.objects.filter(user=user)


class ProductsPurchasedView(LoginRequiredMixin, ListView):
    template_name = 'accounts/dashboard_product_purchased.html'
    context_object_name = 'products_purchased'

    def get_queryset(self):
        user = self.request.user
        products_purchased = []
        order = Order.objects.filter(user=user, paid=True)
        for item in order:
            orderitem = OrderItem.objects.filter(order=item)
            for item in orderitem:
                products_purchased.append(item.product)
        return products_purchased

# class UserLoginView(TemplateView):
#     template_name = 'accounts/login_choice.html'

def UserLoginView(request):
    if not request.user.is_authenticated:
        return render(request, 'accounts/login_choice.html')
    else:
        return redirect('accounts:user_personal_info')


class ApiView(TemplateView):
    template_name = 'accounts/API_info.html'


def user_login_pw(request):
    if request.method == 'POST':
        form = LoginWithPwForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, phone=cd['phone'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(
                    request, 'you loggined successfully', 'success')
                return redirect('accounts:user_personal_info')
            else:
                messages.error(
                    request, 'username or password is incorrect', 'warning')
    else:
        form = LoginWithPwForm()
    context = {'loginform': form}
    return render(request, 'accounts/login_with_password.html', context)


def user_login_code(request):
    if request.method == 'POST':
        form = LoginWithCodeForm(request.POST)
        if form.is_valid():
            phone = form.cleaned_data['phone']
            code = randint(1000, 9999)
            request.session['verify_code'] = code
            request.session['phone'] = phone
            print("="*30)
            print(f'verify code is : {code}')
            print("="*30)
            return redirect('accounts:login_verify_code')
    else:
        form = LoginWithCodeForm()

    context = {
        'loginform': form,
        }
    return render(request, 'accounts/login_with_code.html', context)


def login_verify_code(request):
    code = request.session['verify_code']
    phone = request.session['phone']
    if request.method == 'POST':
        form = VerifyCodeForm(request.POST)
        if form.is_valid():
            if int(code) == int(form.cleaned_data['code']):
                user = get_object_or_404(get_user_model(), phone=phone)
                if user is not None:
                    login(request, user)
                messages.success(request, 'you loggined successfully', 'success')
                return redirect('accounts:user_personal_info')
            else:
                messages.error(request, 'your code is wrong', 'warning')
    else:
        form = VerifyCodeForm()

    context = {'verifycode': form}
    return render(request, 'accounts/login_with_code_verify.html', context)


def user_register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # create account
            user = get_user_model().objects.create_user(cd['phone'], cd['nickname'], cd['phone'])
            if user is not None:
                login(request, user)
            messages.success(request, 'you successfully registered and now you can verify you account or enter your account without verifing', 'success')
            # verify account section 
            phone = cd['phone']
            code = randint(1000, 9999)
            request.session['verify_code'] = code
            request.session['phone'] = phone
            print("="*30)
            print(f'verify code is : {code}')
            print("="*30)
            return redirect('accounts:register_verify_phone')
    else:
        form = UserCreationForm()
    context = {
        'registerform': form
    }
    return render(request, 'accounts/register.html', context)


def register_verify_phone(request):
    code = request.session['verify_code']
    phone = request.session['phone']
    if request.method == 'POST':
        form = VerifyCodeForm(request.POST)
        if form.is_valid():
            if int(code) == int(form.cleaned_data['code']):
                user = get_object_or_404(User, phone=phone)
                user.is_verify = True
                user.save()
                if user is not None:
                    login(request, user)
                messages.success(request, 'your account verfied successfully and you logged in', 'success')
                return redirect('accounts:user_personal_info')
    else:
        form = VerifyCodeForm()
    context = {
        'verify_registerform': form
    }
    return render(request, 'accounts/register_verify.html', context)


@login_required
def user_logout(request):
    logout(request)
    messages.success(request, 'you logged out successfully', 'success')
    return redirect('shop:home')

accounts/templates/accounts/dashboard_base.html
{% extends 'base.html' %}
{% load static %}
{% block title %}| Account{% endblock title %}
{% block page_title %}Account
{% block account_breadcrumb_title %}{% endblock account_breadcrumb_title %}{% endblock page_title %}
{% block breadcrumbs %}
<li>Account</li>
<li>{% block account_breadcrumb %}{% endblock account_breadcrumb %}</li>
{% endblock %}
{% block content %}
<section class="item-details section">
    <div class="container">
        <div class="top-area">
            <div class="row">
                <div class="col-lg-2 col-md-12 col-12">
                    <div class="nav flex-column me-3">
                        {% if user.image %}
                        <img src="{{user.image.url}}" class="rounded mx-auto mb-2" width="100" alt="">
                        {% else %}
                        <i class="bi bi-person-bounding-box text-center display-1"></i>
                        {% comment %} <img src="{% static 'images/avatar.jpg' %}" class="rounded mx-auto" width="100" height="100" alt=""> {% endcomment %}
                        {% endif %}
                        {% if user.nickname %}
                        <p class="mx-auto fs-5">{{user.nickname}}</p>
                        {% elif user.first_name and user.last_name %}
                        <p class="mx-auto fs-5">{{user.first_name}} {{user.last_name}}</p>
                        {% else %}
                        <p class="mx-auto fs-5">{{user.phone}}</p>
                        {% endif %}
                        <hr>
                    </div>
                    <div>
                        <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist"
                            aria-orientation="vertical">
                            <a href="{% url 'accounts:user_personal_info' %}" class="nav-link active mb-1 text-center"
                                type="button">Personal Info</a>
                            <a href="{% url 'accounts:user_wish_list' %}" class="nav-link active mb-1 text-center"
                                type="button">Wishlist</a>
                            <a href="{% url 'accounts:products_purchased' %}" class="nav-link active mb-1 text-center"
                                type="button">Purchases</a>
                            <a href="{% url 'accounts:api_info' %}" class="nav-link active mb-1 text-center" type="button">API document</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 col-12 mx-auto">
                    {% block dashboard %}{%endblock %}
                </div>
                <div class="col-lg-3 col-md-12 col-12">
                    <h3><i class="bi bi-info-square"></i> Tips</h3>
                    <p>{% block tips %}{% endblock tips %}</p>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
{% endblock content %}

accounts/templates/accounts/dashboard_personal_info.html
{% extends 'accounts/dashboard_base.html' %}
{% block title %}| Personal Info{% endblock title %}
{% block account_breadcrumb_title %}| Personal Info{% endblock account_breadcrumb_title %}
{% block account_breadcrumb %}Personal Info{% endblock account_breadcrumb %}

{% block dashboard %}
<div class="row">
<div class="col"><h3>Personal Info</h3></div>
<div class="col"><a href="{% url 'accounts:user_personal_info_edit' request.user.id %}" class="float-end"><i class="bi bi-pencil-square" style="font-size:2em"></i></a></div>
</div>
<hr>
<table class="table table-borderless">
    <tr>
        <td>phone</td>
        <td>{{user.phone}}</td>
    </tr>
    <tr>
        <td>NickName</td>
        <td>{% if user.nickname %}{{user.nickname}}{% else %}--{% endif %}</td>
    </tr>
    <tr>
        <td>FirstName</td>
        <td>{% if user.first_name %}{{user.first_name}}{% else %}--{% endif %}</td>
    </tr>
    <tr>
        <td>LastName</td>
        <td>{% if user.last_name %}{{user.last_name}}{% else %}--{% endif %}</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>{% if user.email %}{{user.email}}{% else %}--{% endif %}</td>
    </tr>
    <tr>
        <td>Bio</td>
        <td>{% if user.bio %}{{user.bio}}{% else %}--{% endif %}</td>
    </tr>
</table>
{% endblock %}
{% block tips %}
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard
dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen
book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially
unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more
recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
{% endblock tips %}

accounts/templates/accounts/dashboard_personal_info_edit.html
{% extends 'accounts/dashboard_base.html' %}
{% block title %}| Personal Info Edit{% endblock title %}
{% block account_breadcrumb_title %}| Personal Info{% endblock account_breadcrumb_title %}
{% block account_breadcrumb %}Edit{% endblock account_breadcrumb %}

{% block dashboard %}
<div class="row">
    <div class="col">
        <h3>Update Personal Info</h3>
    </div>
</div>
<hr>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="fieldWrapper mb-3">
        {{ form.image.errors }}
        <label for="{{ form.image.id_for_label }}" class="form-label">Image :</label>
        <input type="file" name="image" value='{{ request.user.image }}' id="id_image" class='form-control'>
    </div>
    <div class="fieldWrapper mb-3">
        {{ form.email.errors }}
        <label for="{{ form.email.id_for_label }}" class="form-label">Email :</label>
        <input type="email" name="email" placeholder='Email' value='{{ request.user.email }}' maxlength="100"
            id="id_email" class='form-control'>
    </div>
    <div class="fieldWrapper mb-3">
        {{ form.nickname.errors }}
        <label for="{{ form.nickname.id_for_label }}" class="form-label">NickName :</label>
        <input type="text" name="nickname" placeholder='NickName' value='{{ request.user.nickname }}' maxlength="100"
            id="id_nickname" class='form-control'>
    </div>
    <div class="fieldWrapper mb-3">
        {{ form.first_name.errors }}
        <label for="{{ form.first_name.id_for_label }}" class="form-label">First Name :</label>
        <input type="text" name="first_name" placeholder='First Name' value='{{ request.user.first_name }}'
            maxlength="100" id="id_first_name" class='form-control'>
    </div>
    <div class="fieldWrapper mb-3">
        {{ form.last_name.errors }}
        <label for="{{ form.last_name.id_for_label }}" class="form-label">Last Name :</label>
        <input type="text" name="last_name" placeholder='Last Name' value='{{ request.user.last_name }}' maxlength="100"
            id="id_last_name" class='form-control'>
    </div>
    <div class="fieldWrapper mb-3">
        {{ form.bio.errors }}
        <label for="{{ form.bio.id_for_label }}" class="form-label">Bio :</label>
        <input type="text" name="bio" placeholder="Bio" value='{{ request.user.bio }}' maxlength="100" id="id_bio"
            class="form-control">
    </div>
    <input type="submit" value="Update" class="btn btn-outline-primary">
    <a href={% url 'accounts:user_personal_info' %} class="btn btn-outline-secondary">Cancel</a>
</form>
{% endblock %}
{% block tips %}
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard
dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen
book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially
unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more
recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
{% endblock tips %}

accounts/templates/accounts/dashboard_product_purchased.html
{% extends 'accounts/dashboard_base.html' %}
{% block title %}| Purchases{% endblock title %}
{% block account_breadcrumb_title %}| Purchases{% endblock account_breadcrumb_title %}
{% block account_breadcrumb %}Purchases{% endblock account_breadcrumb %}


{% block dashboard %}
<div class="row">
    <div class="col">
        <h3>Products purchased</h3>
    </div>
</div>
<hr>
{% for item in  products_purchased %}
<div class="card mb-2 shadow-sm bg-body rounded border-0">
  <div class="row">
    <div class="col-md-2">
      <a href="{% url 'shop:product_detail' item.slug %}"><img src="{{item.image.url}}" class="rounded-start"
          alt="{{item.name}}"></a>
    </div>
    <div class="col-md-9">
      <a href="{% url 'shop:product_detail' item.slug %}">
        <h5 class="card-title pt-3">{{item.name}}</h5>
      </a>
      <p class="card-text"><a href="#"><small class="text-muted">{{item.subcategory}}</small></a></p>

    </div>
    <div class="col-md-1">
      <div class="btn-group float-end">
        <button type="button" class="btn" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-three-dots-vertical"></i>
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'shop:product_detail' item.slug %}">product detail</a></li>
        </ul>
      </div>
    </div>

  </div>
</div>
{% endfor %}
{% endblock %}
{% block tips %}
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard
dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen
book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially
unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more
recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
{% endblock tips %}

accounts/templates/accounts/dashboard_wishlist.html
{% extends 'accounts/dashboard_base.html' %}
{% block title %}| WishList{% endblock title %}
{% block account_breadcrumb_title %}| WishList{% endblock account_breadcrumb_title %}
{% block account_breadcrumb %}WishList{% endblock account_breadcrumb %}


{% block dashboard %}
<div class="row">
    <div class="col">
        <h3>Wishlist</h3>
    </div>
</div>
<hr>
{% for item in wishlists %}
{% for product in item.product.all %}
<div class="card mb-2 shadow-sm bg-body rounded border-0">
  <div class="row">
    <div class="col-md-2">
      <img src="{{product.image.url}}" class="rounded-start" alt="{{product.name}}">
    </div>
    <div class="col-md-9">
      <h5 class="card-title pt-3">{{product.name}}</h5>
      <p class="card-text"><a href="#"><small class="text-muted">{{product.subcategory}}</small></a></p>

    </div>
    <div class="col-md-1">
      <div class="btn-group float-end">
        <button type="button" class="btn" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-three-dots-vertical"></i>
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'wishlist:remove_wishlist' product.id %}">Remove</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endfor %}
{% endblock %}
{% block tips %}
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard
dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen
book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially
unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more
recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
{% endblock tips %}

accounts/templates/accounts/login_choice.html
{% extends 'base.html' %}
{% block content %}
<div class="account-login section">
    <div class="container">
        <div class="row">

            <div class="col-lg-6 offset-lg-3 col-md-10 offset-md-1 col-12">
                <div class="card login-form">
                    <!-- start login with code form -->
                    <div class="card-body">
                        <div class="title">
                            <h3>Login Now</h3>
                            <p>please select one of this way that you comfortable login to your account</p>
                        </div>
                        <!-- start login form -->
                        <div class="row col-6 mx-auto d-block">
                                <a href={% url 'accounts:user_login_with' %} class="btn btn-outline-primary mb-1">login
                                    with password</a>
                                <a href={% url 'accounts:user_login_code' %} class="btn btn-outline-primary">login with
                                    code</a>
                        </div>


                    </div>

                    <!-- end login form -->
                </div>
                <!-- end login with code form-->
            </div>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="account-login section">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 offset-lg-3 col-md-10 offset-md-1 col-12">
        <div class="register-form">
          <div class="title">
            <h3>No Account? Register</h3>
            <p>
              Registration takes less than a minute but gives you full control
              over your orders.
            </p>
          </div>
          <form class="row" method="post">
            <div class="col-sm-12">
              <div class="form-group">
              <form action="" method="post">
              {% csrf_token %}
              {{registerform}}
              </form>
              <div class="button">
              <button class="btn" type="submit">Register</button>
            </div>
              </div>
            </div>
            
            <p class="outer-link">
              Already have an account? <a href="{% url 'accounts:user_login' %}">Login Now</a>
            </p>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

accounts/templates/accounts/register_verify.html
{% extends 'base.html' %}

{% block content %}
<div class="account-login section">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 offset-lg-3 col-md-10 offset-md-1 col-12">
        <div class="register-form">
          <div class="title">
            <h3>No Account? Register</h3>
            <p>
              Registration takes less than a minute but gives you full control
              over your orders.
            </p>
          </div>
          <form class="row" method="post">
            <div class="col-sm-12">
              <div class="form-group">
                <form action="" method="post">
                  {% csrf_token %}
                  {{verify_registerform}}
                </form>
                <div class="button">
                  <button class="btn" type="submit">Verify</button>
                </div>
              </div>
            </div>

            <p class="outer-link">
              Already have an account? <a href="{% url 'accounts:user_login' %}">Login Now</a>
            </p>
          </form>
          <a href="{% url 'accounts:user_personal_info' %}">Enter your account</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}