blog/urls.py
from django.urls import path
from .views import AllArticleListView, SingleArticleView, CategoryArticleListView

app_name = 'blog'
urlpatterns = [
    path('', AllArticleListView.as_view(), name='article_list'),
    path('c/<slug:slug>/', CategoryArticleListView.as_view(), name='category_article_list'),
    path('article/<slug:slug>/', SingleArticleView.as_view(), name='article_detail'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.CartDetailView.as_view() , name='cart_detail'),
    path('add/<int:product_id>', views.cart_product_add, name='card_add'),
    path('addtocart/<int:product_id>', views.add_to_cart, name='card_to_add'),
    path('remove/<int:product_id>', views.cart_product_remove, name='card_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from rest_framework_simplejwt import views as jwt_views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Shop API",
      default_version='v1',
      description="All endpoints of this shop",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="support@shop.com"),
      license=openapi.License(name="GPLv3 License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    #all project apps urls
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('', include('shop.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog')),
    #all api urls
    path('api-auth/', include('rest_framework.urls')),
    path('api/rest-auth/', include('dj_rest_auth.urls')),
    path('api/products/', include('shop_api.urls')),
    path('api/accounts/', include('accounts_api.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

shop/urls.py
from django.urls import path
from . import views
from . import context_processors


app_name = 'shop'
urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('p/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('search/', views.SearchProductListView.as_view(), name='product_search'),
    path('c/<slug:slug>/', views.CategoryProductListView.as_view(), name='category_product_list'),
    path('c/<slug:slug>/lowprice-products/', views.LowPriceProductsView.as_view(), name='lowprice'),
    path('c/<slug:slug>/highprice-products/', views.HighPriceProductsView.as_view(), name='highprice'),
    path('c/<slug:slug>/a-to-z-products/', views.AZNameProductsView.as_view(), name='a-to-z-name'),
    path('c/<slug:slug>/z-to-a-products/', views.ZANameProductsView.as_view(), name='z-to-a-name'),
    path('about-us', views.AboutUsView.as_view(), name='about-us'),
    path('contact-us', views.ContactUsView.as_view(), name='contact-us'),
]

wishlist/urls.py
from django.urls import path
from .views import WishListView, RemoveWishListView, AddWishListView


app_name = 'wishlist'
urlpatterns = [
    path('', WishListView.as_view(), name='wishlist'),
    path('add/<int:id>/<slug:slug>/', AddWishListView.as_view(), name='add_wishlist'),
    path('remove/<int:id>/', RemoveWishListView.as_view(), name='remove_wishlist'),
]

shop/models.py
from django.db import models


class MainCategory(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name

class SubCategory(models.Model):
    maincategory = models.ForeignKey(MainCategory, related_name='subcategories', on_delete=models.CASCADE)
    name = models.CharField(max_length=150,null=True, blank=True, unique=True)
    slug = models.SlugField(max_length=150, unique=True, null=True, blank=True)

    def __str__(self):
        return self.name
        verbose_name = 'SubCategory'
        verbose_name_plural = 'SubCategories'

class Product(models.Model):
    maincategory = models.ForeignKey(MainCategory, on_delete=models.CASCADE, null=True)
    subcategory = models.ForeignKey(SubCategory,on_delete=models.CASCADE, blank=True, null=True)
    name  = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/')
    description = models.TextField(blank=True, null=True)
    short_description = models.TextField(blank=True, null=True)
    specifications = models.TextField(blank=True, null=True)
    discount = models.IntegerField(blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    stock = models.IntegerField(null=True, blank=True)
    available = models.BooleanField(default=True)
    shipping = models.FloatField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
    
    def __str__(self):
        return self.name
    
    def price_after_set_discount(self):
        calculate_set_discount = (self.price*self.discount)/100
        total_price = self.price - calculate_set_discount
        return total_price

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import MainCategory, Product
from django.views.generic import ListView, TemplateView
from django.views.generic.detail import DetailView
from django.views import View
from cart.forms import CartAddForm
from django.views.generic.edit import FormMixin
from django.urls import reverse_lazy
from wishlist.models import WishList
from django.conf import settings
from django.db.models import Q



class HomePage(View):
    products = Product.objects.filter(available=True)[:8]
    context = {'products':products}
    def get(self, request, *args, **kwargs):
        return render(request,'home.html', self.context)


class AboutUsView(TemplateView):
    template_name = 'about_us.html'

class ContactUsView(TemplateView):
    template_name = 'contact_us.html'


class FooterInformationView(View):
    template_name = 'base.html'
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = MainCategory.objects.all()
        return context

class CategoryProductListView(ListView):
    model = Product
    template_name = 'shop/category_product_list.html'
    paginate_by = 9

    def get_queryset(self, *args, **kwargs):
        queryset = super(CategoryProductListView, self).get_queryset()
        category = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        return Product.objects.filter(available=True, maincategory=category).order_by('-created')

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        category = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        context['category'] = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        return context

class ProductDetailView(FormMixin, DetailView):
    model = Product
    context_object_name = 'product'
    form_class = CartAddForm
    success_url = reverse_lazy('cart:detail')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        wishlist_product = []
        if self.request.user.is_authenticated:
            user_wishlist = WishList.objects.filter(user=self.request.user)
            for item in user_wishlist:
                for product in item.products.all():
                    wishlist_product.append(product.name)
        context['wishlist_product'] = wishlist_product
        return context


class SearchProductListView(ListView):
    template_name = 'shop/search_list.html'
    context_object_name = 'searched_products'
    paginate_by = 9

    def get_queryset(self):
        search = self.request.GET.get('q', default="")
        return Product.objects.filter(Q(name__icontains=search) | Q(description__icontains=search))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context
    
class LowPriceProductsView(ListView):
    model = Product
    template_name = 'shop/category_product_list.html'
    paginate_by = 9

    def get_queryset(self, *args, **kwargs):
        queryset = super(LowPriceProductsView, self).get_queryset()
        category = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        return Product.objects.filter(available=True, maincategory=category).order_by('price')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        context['category'] = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        context['sorting'] = "Low - High Price"
        return context

class HighPriceProductsView(ListView):
    model = Product
    template_name = 'shop/category_product_list.html'
    paginate_by = 9

    def get_queryset(self, *args, **kwargs):
        queryset = super(HighPriceProductsView, self).get_queryset()
        category = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        return Product.objects.filter(available=True, maincategory=category).order_by('-price')
        
    def get_context_data(self, **kwargs):
        context  = super().get_context_data(**kwargs)
        category = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        context['category'] = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        context['sorting'] = "High - Low Price"
        return context


class AZNameProductsView(ListView):
    model = Product
    template_name = 'shop/category_product_list.html'
    paginate_by = 9

    def get_queryset(self, *args, **kwargs):
        queryset = super(AZNameProductsView, self).get_queryset()
        category = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        return Product.objects.filter(available=True, maincategory=category).order_by('name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        context['category'] = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        context['sorting'] = "A - Z Order"
        return context


class ZANameProductsView(ListView):
    model = Product
    template_name = 'shop/category_product_list.html'
    paginate_by = 9

    def get_queryset(self, *args, **kwargs):
        queryset = super(ZANameProductsView, self).get_queryset()
        category = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        return Product.objects.filter(available=True, maincategory=category).order_by('-name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        context['category'] = get_object_or_404(MainCategory, slug=self.kwargs['slug'])
        context['sorting'] = "Z - A Order"
        return context

shop/templates/shop/category_product_list.html
{% extends 'base.html' %} 
{% block title %}| {{category.name}}{% endblock title %}
{% block page_title %}{{category.name}}{% endblock page_title %}
{% block breadcrumbs %}{{ block.super }}Products({{category.name}}){% endblock %}

{% block content %}
<section class="product-grids section">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-12">
        <div class="product-sidebar">
          <div class="single-widget search">
            <h3>Search Product</h3>
            <form action="{% url 'shop:product_search' %}">
              <input type="text" placeholder="Search" name='q' />
              <button type="submit"><i class="lni lni-search-alt"></i></button>
            </form>
          </div>
          <div class="single-widget">
            <h3>All Categories</h3>
            <ul class="list">
              {% for category in categories %}
              <li>
                <a href="product-grids.html">{{category.name}}</a><span></span>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-9 col-12">
        <div class="product-grids-head">
        {% if page_obj %}
        <div class="product-grid-topbar">
            <div class="row align-items-center">
              <div class="col-lg-7 col-md-8 col-12">
                <div class="product-sorting">
                  <label for="sorting">Sort by:</label>
                  <select class="form-control" id="sorting_product" onchange="location=this.value;">
                    <option value="{% url 'shop:home' %}">-- Select --</option>
                    <option value="{% url 'shop:lowprice' category.slug %}">Low - High Price</option>
                    <option value="{% url 'shop:highprice' category.slug %}">High - Low Price</option>
                    <option value="{% url 'shop:a-to-z-name' category.slug %}">A - Z Order</option>
                    <option value="{% url 'shop:z-to-a-name' category.slug %}">Z - A Order</option>
                    <option hidden="hidden" id='sorting' value="{{sorting}}"></option>
                  </select>
                  <h3 class="total-show-product">
                    Showing: <span>1 - {{ page_obj.object_list | length }} items</span>
                  </h3>
                </div>
              </div>
              <div class="col-lg-5 col-md-4 col-12">
                <nav>
                  <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-grid-tab" data-bs-toggle="tab" data-bs-target="#nav-grid"
                      type="button" role="tab" aria-controls="nav-grid" aria-selected="true">
                      <i class="lni lni-grid-alt"></i>
                    </button>
                    <button class="nav-link" id="nav-list-tab" data-bs-toggle="tab" data-bs-target="#nav-list"
                      type="button" role="tab" aria-controls="nav-list" aria-selected="false">
                      <i class="lni lni-list"></i>
                    </button>
                  </div>
                </nav>
              </div>
            </div>
          </div>
          {% else %}
          <div class="product-grid-topbar">
            <div class="row align-items-center">
              <div class="col-lg-7 col-md-8 col-12">
              <p>There is no product in <span style='color:#0167f3'>{{category}}</span> category</p>
              </div>
            </div>
          </div>
        {% endif %}
          <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-grid" role="tabpanel" aria-labelledby="nav-grid-tab">
              <div class="row">
                {% for product in page_obj %}
                <div class="col-lg-4 col-md-6 col-12">
                  <div class="single-product">
                    <div class="product-image">
                      <a href="{% url 'shop:product_detail' product.slug %}"><img src="{{product.image.url}}"
                          alt="#" /></a>
                      <div class="button">
                        <a href="{% url 'cart:card_to_add' product.id %}" class="btn"><i class="lni lni-cart"></i> Add
                          to Cart</a>
                      </div>
                    </div>
                    <div class="product-info">
                      <span class="category">{{product.subcategory}}</span>
                      <h4 class="title">
                        <a href="{% url 'shop:product_detail' product.slug %}">{{product.name}}</a>
                      </h4>
                      <ul class="review">
                        <li><i class="lni lni-star-filled"></i></li>
                        <li><i class="lni lni-star-filled"></i></li>
                        <li><i class="lni lni-star-filled"></i></li>
                        <li><i class="lni lni-star-filled"></i></li>
                        <li><i class="lni lni-star"></i></li>
                        <li><span>4.0 Review(s)</span></li>
                      </ul>
                      <div class="price">
                        <span>${{product.price}}</span>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
            
              {% include 'inc/paginator.html' %}
            </div>
            <div class="tab-pane fade" id="nav-list" role="tabpanel" aria-labelledby="nav-list-tab">
              <div class="row">
                {% for product in page_obj %}
                <div class="col-lg-12 col-md-12 col-12">
                  <div class="single-product">
                    <div class="row align-items-center">
                      <div class="col-lg-4 col-md-4 col-12">
                        <div class="product-image">
                          <a href="{% url 'shop:product_detail' product.slug %}"><img src="{{product.image.url}}"
                              alt="#" /></a>
                          <span class="sale-tag">-25%</span>
                          <div class="button">
                            <a href="{% url 'cart:card_to_add' product.id %}" class="btn"><i class="lni lni-cart"></i>
                              Add to Cart</a>
                          </div>
                        </div>
                      </div>
                      <div class="col-lg-8 col-md-8 col-12">
                        <div class="product-info">
                          <span class="category">{{product.subcategory}}</span>
                          <h4 class="title">
                            <a href="{% url 'shop:product_detail' product.slug %}">{{product.name}}</a>
                          </h4>
                          <ul class="review">
                            <li><i class="lni lni-star-filled"></i></li>
                            <li><i class="lni lni-star-filled"></i></li>
                            <li><i class="lni lni-star-filled"></i></li>
                            <li><i class="lni lni-star-filled"></i></li>
                            <li><i class="lni lni-star-filled"></i></li>
                            <li><span>5.0 Review(s)</span></li>
                          </ul>
                          <div class="price">
                            <span>${{product.price}}</span>
                            <span class="discount-price">$300.00</span>
                          </div>
                          <div>
                            <span>{{product.short_description}}</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
              {% include 'inc/paginator.html' %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

shop/templates/shop/product_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block title %}| {{product.name}}{% endblock title %}
{% block page_title %}{{product.name}}{% endblock page_title %}
{% block breadcrumbs %}
<li><a href="{% url 'shop:category_product_list' product.maincategory.slug %}">{{product.maincategory}}</a></li>
<li>{{product.name}}</li>
{% endblock %}
{% block content %}
<!-- Start Item Details -->
<section class="item-details section">
    <div class="container">
        <div class="top-area">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-12 col-12">
                    <div class="product-images">
                        <main id="gallery">
                            <div class="main-img">
                                <img src="{{product.image.url}}" id="current" alt="#">
                            </div>
                        </main>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 col-12">
                    <div class="product-info">
                        <h2 class="title">{{product.name}}</h2>{{product.subcategory}}</a></p><br>
                        {% if product.discount %}
                        {% if product.price_after_set_discount == 0 %}
                        <h3 class="price">FREE</h3>
                        {% else %}
                        <h3 class="price">${{product.price_after_set_discount|intcomma}}<span>${{product.price|intcomma}}</span></h3>
                        {% endif %}
                        {% else %}
                        <h3 class="price">${{product.price|intcomma}}</h3 {% endif %} <p class="info-text">
                        {{product.short_description}}</p>
                        <div class="row">
                        </div>
                        <div class="bottom-content">
                            <div class="row align-items-end">
                                <div class="col-lg-4 col-md-4 col-12">
                                    <div class="form-group quantity">
                                        <form action="{% url 'cart:card_add' product.id %}" method="post">
                                            {% csrf_token %}
                                            {{form}}
                                            <div class="wish-button">
                                                <button type="submit" class="btn mt-1"><i class="bi bi-cart-plus"></i>
                                                    Add to Cart</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                {% comment %} <div class="col-lg-4 col-md-4 col-12">
                                    <div class="wish-button">
                                        <button class="btn"><i class="lni lni-reload"></i> Compare</button>
                                    </div>
                                </div> {% endcomment %}
                                <div class="col-lg-4 col-md-4 col-12">
                                    <div class="wish-button">
                                        {% if product.name not in wishlist_product %}
                                        <a href="{% url 'wishlist:add_wishlist' product.id product.slug %}" class="btn">
                                            <i class="lni lni-heart"></i> To Wishlist
                                        </a>
                                        {% else %}
                                        <a href="{% url 'wishlist:remove_wishlist' product.id %}" class="btn-active">
                                            <i class="lni lni-heart"></i> Remove
                                        </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="product-details-info">
            <div class="single-block">
                <div class="row">
                    <div class="col-lg-12 col-12">
                        <div class="info-body">
                            <h4>Specifications</h4>
                            <ul class="normal-list">
                                {{product.specifications | linebreaks}}
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12 col-12">
                        <div class="info-body custom-responsive-margin">
                            <h4>Details</h4>
                            <p>{{product.description}}</p>
                            <h4>Features</h4>
                            <ul class="features">
                                <li>Capture 4K30 Video and 12MP Photos</li>
                                <li>Game-Style Controller with Touchscreen</li>
                                <li>View Live Camera Feed</li>
                                <li>Full Control of HERO6 Black</li>
                                <li>Use App for Dedicated Camera Operation</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Item Details -->

<!-- Review Modal -->
<div class="modal fade review-modal" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Leave a Review</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="review-name">Your Name</label>
                            <input class="form-control" type="text" id="review-name" required>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="review-email">Your Email</label>
                            <input class="form-control" type="email" id="review-email" required>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="review-subject">Subject</label>
                            <input class="form-control" type="text" id="review-subject" required>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="review-rating">Rating</label>
                            <select class="form-control" id="review-rating">
                                <option>5 Stars</option>
                                <option>4 Stars</option>
                                <option>3 Stars</option>
                                <option>2 Stars</option>
                                <option>1 Star</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="review-message">Review</label>
                    <textarea class="form-control" id="review-message" rows="8" required></textarea>
                </div>
            </div>
            <div class="modal-footer button">
                <button type="button" class="btn">Submit Review</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}