accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    # user dashboard urls
    path('personal-info/', views.PersonalInfoView.as_view(), name='user_personal_info'),
    path('personal-info/<int:pk>/edit/', views.PersonalInfoEditView.as_view(), name='user_personal_info_edit'),
    path('wishlist/', views.WishListView.as_view(), name='user_wish_list'),
    path('products-purchased/', views.ProductsPurchasedView.as_view(), name='products_purchased'),
    path('api-info/', views.ApiView.as_view(), name='api_info'),
    # register login and logout urls
    path('login/', views.UserLoginView, name='user_login'),
    path('login/with-password/', views.user_login_pw, name='user_login_with'),
    path('login/with-code/', views.user_login_code, name='user_login_code'),
    path('login/with-code/verify/', views.login_verify_code, name='login_verify_code'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.user_register, name='user_register'),
    path('register/verify/', views.register_verify_phone, name='register_verify_phone'),    
]

blog/urls.py
from django.urls import path
from .views import AllArticleListView, SingleArticleView, CategoryArticleListView

app_name = 'blog'
urlpatterns = [
    path('', AllArticleListView.as_view(), name='article_list'),
    path('c/<slug:slug>/', CategoryArticleListView.as_view(), name='category_article_list'),
    path('article/<slug:slug>/', SingleArticleView.as_view(), name='article_detail'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.CartDetailView.as_view() , name='cart_detail'),
    path('add/<int:product_id>', views.cart_product_add, name='card_add'),
    path('addtocart/<int:product_id>', views.add_to_cart, name='card_to_add'),
    path('remove/<int:product_id>', views.cart_product_remove, name='card_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from rest_framework_simplejwt import views as jwt_views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Shop API",
      default_version='v1',
      description="All endpoints of this shop",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="support@shop.com"),
      license=openapi.License(name="GPLv3 License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    #all project apps urls
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('', include('shop.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog')),
    #all api urls
    path('api-auth/', include('rest_framework.urls')),
    path('api/rest-auth/', include('dj_rest_auth.urls')),
    path('api/products/', include('shop_api.urls')),
    path('api/accounts/', include('accounts_api.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

shop/urls.py
from django.urls import path
from . import views
from . import context_processors


app_name = 'shop'
urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('p/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('search/', views.SearchProductListView.as_view(), name='product_search'),
    path('c/<slug:slug>/', views.CategoryProductListView.as_view(), name='category_product_list'),
    path('c/<slug:slug>/lowprice-products/', views.LowPriceProductsView.as_view(), name='lowprice'),
    path('c/<slug:slug>/highprice-products/', views.HighPriceProductsView.as_view(), name='highprice'),
    path('c/<slug:slug>/a-to-z-products/', views.AZNameProductsView.as_view(), name='a-to-z-name'),
    path('c/<slug:slug>/z-to-a-products/', views.ZANameProductsView.as_view(), name='z-to-a-name'),
    path('about-us', views.AboutUsView.as_view(), name='about-us'),
    path('contact-us', views.ContactUsView.as_view(), name='contact-us'),
]

wishlist/urls.py
from django.urls import path
from .views import WishListView, RemoveWishListView, AddWishListView


app_name = 'wishlist'
urlpatterns = [
    path('', WishListView.as_view(), name='wishlist'),
    path('add/<int:id>/<slug:slug>/', AddWishListView.as_view(), name='add_wishlist'),
    path('remove/<int:id>/', RemoveWishListView.as_view(), name='remove_wishlist'),
]

templates/inc/breadcrumbs.html
<div class="breadcrumbs">
<div class="container">
<div class="row align-items-center">
<div class="col-lg-6 col-md-6 col-12">
<div class="breadcrumbs-content">
<h1 class="page-title">Single Product</h1>
</div>
</div>
<div class="col-lg-6 col-md-6 col-12">
<ul class="breadcrumb-nav">
<li><a href="index.html"><i class="lni lni-home"></i> Home</a></li>
<li><a href="index.html">Shop</a></li>
<li>Single Product</li>
</ul>
</div>
</div>
</div>
</div>

templates/inc/footer.html
{% load static %}
<!-- Start Shipping Info -->
<section class="shipping-info">
  <div class="container">
    <ul>
      <!-- Free Shipping -->
      <li>
        <div class="media-icon">
          <i class="lni lni-delivery"></i>
        </div>
        <div class="media-body">
          <h5>Free Shipping</h5>
          <span>On order over $99</span>
        </div>
      </li>
      <!-- Money Return -->
      <li>
        <div class="media-icon">
          <i class="lni lni-support"></i>
        </div>
        <div class="media-body">
          <h5>24/7 Support.</h5>
          <span>Live Chat Or Call.</span>
        </div>
      </li>
      <!-- Support 24/7 -->
      <li>
        <div class="media-icon">
          <i class="lni lni-credit-cards"></i>
        </div>
        <div class="media-body">
          <h5>Online Payment.</h5>
          <span>Secure Payment Services.</span>
        </div>
      </li>
      <!-- Safe Payment -->
      <li>
        <div class="media-icon">
          <i class="lni lni-reload"></i>
        </div>
        <div class="media-body">
          <h5>Easy Return.</h5>
          <span>Hassle Free Shopping.</span>
        </div>
      </li>
    </ul>
  </div>
</section>
<!-- End Shipping Info -->

<!-- Start Footer Area -->
<footer class="footer">
  <!-- Start Footer Middle -->
  <div class="footer-middle">
    <div class="container">
      <div class="bottom-inner">
        <div class="row">
          <div class="col-lg-3 col-md-6 col-12">
            <!-- Single Widget -->
            <div class="single-footer f-contact">
              <h3>Get In Touch With Us</h3>
              <p class="phone">Phone: +98 (930) 252 1022</p>
              <ul>
                <li><span>Saturday-Thursday: </span> 8.00 am - 8.00 pm</li>
                <li><span>Friday: </span> 10.00 am - 6.00 pm</li>
              </ul>
              <p class="mail">
                <a href="mailto:#">support@store.com</a>
              </p>
            </div>
            <!-- End Single Widget -->
          </div>
          <div class="col-lg-3 col-md-6 col-12">
            <!-- Single Widget -->
            <div class="single-footer our-app">
              <h3>Our Mobile App</h3>
              <ul class="app-btn">
                <li>
                  <a href="javascript:void(0)">
                    <i class="lni lni-apple"></i>
                    <span class="small-title">Download on the</span>
                    <span class="big-title">App Store</span>
                  </a>
                </li>
                <li>
                  <a href="javascript:void(0)">
                    <i class="lni lni-play-store"></i>
                    <span class="small-title">Download on the</span>
                    <span class="big-title">Google Play</span>
                  </a>
                </li>
              </ul>
            </div>
            <!-- End Single Widget -->
          </div>
          <div class="col-lg-3 col-md-6 col-12">
            <!-- Single Widget -->
            <div class="single-footer f-link">
              <h3>Information</h3>
              <ul>
                <li><a href="{% url 'shop:about-us' %}">About Us</a></li>
                <li><a href="{% url 'shop:contact-us' %}">Contact Us</a></li>
              </ul>
            </div>
            <!-- End Single Widget -->
          </div>
          <div class="col-lg-3 col-md-6 col-12">
            <!-- Single Widget -->
            <div class="single-footer f-link">
              <h3>Products Categories</h3>
              <ul>
                {% for cat in categories %}
                <li><a href="{% url 'shop:category_product_list' cat.slug %}">{{cat.name}}</a></li>
                {% endfor %}
              </ul>
            </div>
            <!-- End Single Widget -->
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Footer Middle -->
  <!-- Start Footer Bottom -->
  <div class="footer-bottom">
    <div class="container">
      <div class="inner-content">
        <div class="row align-items-center">
          <div class="col-lg-4 col-12">
            <div class="payment-gateway">
              <span>We Accept:</span>
              <img src="{% static 'images/footer/credit-cards-footer.png' %}" alt="#" />
            </div>
          </div>
          <div class="col-lg-4 col-12">
            <div class="copyright">
              <p>
                Designed and Developed by<a href="https://behtashfani.com/" rel="nofollow" target="_blank">Behtash</a>
              </p>
            </div>
          </div>
          <div class="col-lg-4 col-12">
            <ul class="socila">
              <li>
                <span>Follow Us On:</span>
              </li>
              <li>
                <a href="javascript:void(0)"><i class="lni lni-facebook-filled"></i></a>
              </li>
              <li>
                <a href="javascript:void(0)"><i class="lni lni-twitter-original"></i></a>
              </li>
              <li>
                <a href="javascript:void(0)"><i class="lni lni-instagram"></i></a>
              </li>
              <li>
                <a href="javascript:void(0)"><i class="lni lni-google"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Footer Bottom -->
</footer>
<!--/ End Footer Area -->

templates/inc/last_blog_post.html
{% load static %}
<section class="blog-section section">
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="section-title">
          <h2>Our Latest News</h2>
          <p>
            There are many variations of passages of Lorem Ipsum available, but
            the majority have suffered alteration in some form.
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-md-6 col-12">
        <div class="single-blog">
          <div class="blog-img">
            <a href="blog-single-sidebar.html">
              <img src="{% static 'images/blog/blog-1.jpeg' %}" alt="#" />
            </a>
          </div>
          <div class="blog-content">
            <a class="category" href="javascript:void(0)">eCommerce</a>
            <h4>
              <a href="blog-single-sidebar.html"
                >What information is needed for shipping?</a
              >
            </h4>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt.
            </p>
            <div class="button">
              <a href="javascript:void(0)" class="btn">Read More</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-12">
        <div class="single-blog">
          <div class="blog-img">
            <a href="blog-single-sidebar.html">
              <img src="{% static 'images/blog/blog-2.jpeg' %}" alt="#" />
            </a>
          </div>
          <div class="blog-content">
            <a class="category" href="javascript:void(0)">Gaming</a>
            <h4>
              <a href="blog-single-sidebar.html"
                >Interesting fact about gaming consoles</a
              >
            </h4>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt.
            </p>
            <div class="button">
              <a href="javascript:void(0)" class="btn">Read More</a>
            </div>
          </div>
        </div>
      </div>
      {% load static %}
      <div class="col-lg-4 col-md-6 col-12">
        <div class="single-blog">
          <div class="blog-img">
            <a href="blog-single-sidebar.html">
              <img src="{% static 'images/blog/blog-3.jpeg' %}" alt="#" />
            </a>
          </div>
          <div class="blog-content">
            <a class="category" href="javascript:void(0)">Electronic</a>
            <h4>
              <a href="blog-single-sidebar.html"
                >Electronics, instrumentation &amp; control engineering
              </a>
            </h4>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt.
            </p>
            <div class="button">
              <a href="javascript:void(0)" class="btn">Read More</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/inc/messages.html
<div class="container">
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</div>

templates/inc/navbar.html
{% load static %}
<header class="header navbar-area">
    <!-- Start Topbar -->
    <div class="topbar">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 col-md-4 col-12">
                    <div class="top-left">
                        <ul class="menu-top-link">
                            <li>
                                <div class="select-position">
                                    <select id="select4">
                                        <option value="0" selected>$ USD</option>
                                        <option value="1">€ EURO</option>
                                        <option value="2">$ CAD</option>
                                        <option value="3">₹ INR</option>
                                        <option value="4">¥ CNY</option>
                                        <option value="5">৳ BDT</option>
                                    </select>
                                </div>
                            </li>
                            <li>
                                <div class="select-position">
                                    <select id="select5">
                                        <option value="0" selected>English</option>
                                        <option value="1">Español</option>
                                        <option value="2">Filipino</option>
                                        <option value="3">Français</option>
                                        <option value="4">العربية</option>
                                        <option value="5">हिन्दी</option>
                                        <option value="6">বাংলা</option>
                                    </select>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-12">
                    <div class="top-middle">
                        <ul class="useful-links">
                            <li><a href="{% url 'shop:home' %}">Home</a></li>
                            <li><a href="{% url 'shop:about-us' %}">About Us</a></li>
                            <li><a href="{% url 'shop:contact-us' %}">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-12">
                    <div class="top-end">
                        {% if request.user.is_authenticated %}
                        <ul class="user-login">
                            <li>
                                <i class="lni lni-user" style="color: #FFF"></i> <a
                                    href="{% url 'accounts:user_personal_info' %}">Hello
                                    {% if request.user.nickname %}
                                    {{request.user.nickname}}
                                    {% else %}{{request.user.phone}}{% endif %}</a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:user_logout' %}">Sign Out</a>
                            </li>
                        </ul>
                        {% else %}
                        <ul class="user-login">
                            <li>
                                <a href="{% url 'accounts:user_login' %}">Sign In</a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:user_register' %}">Register</a>
                            </li>
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Topbar -->
    <!-- Start Header Middle -->
    <div class="header-middle">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-3 col-7">
                    <!-- Start Header Logo -->
                    <a class="navbar-brand" href="{% url 'shop:home' %}">
                        <img src="{% static 'images/logo/main_logo.svg' %}" alt="Logo">
                    </a>
                    <!-- End Header Logo -->
                </div>
                <div class="col-lg-5 col-md-7 d-xs-none">
                    <!-- Start Main Menu Search -->
                    <div class="main-menu-search">
                        <!-- navbar search start -->
                        <form action="{% url 'shop:product_search' %}">
                            <div class="navbar-search search-style-5">
                                <div class="search-input">
                                    <input type="text" placeholder="Search" name='q'>
                                </div>
                                <div class="search-btn">
                                    <button><i class="lni lni-search-alt"></i></button>
                                </div>
                            </div>
                        </form>
                        <!-- navbar search Ends -->
                    </div>
                    <!-- End Main Menu Search -->
                </div>
                <div class="col-lg-4 col-md-2 col-5">
                    <div class="middle-right-area">
                        <div class="nav-hotline">
                            <i class="lni lni-phone"></i>
                            <h3>Hotline:
                                <span>(+98) 930 252 1022</span>
                            </h3>
                        </div>
                        <div class="navbar-cart">
                            <div class="wishlist">
                                <a href="{% url 'wishlist:wishlist' %}">
                                    <i class="lni lni-heart"></i>
                                    <span class="total-items">{{wishlist_item_count}}</span>
                                </a>
                            </div>

                            <div class="cart-items">
                                <a href="javascript:void(0)" class="main-btn">
                                    <i class="lni lni-cart"></i>
                                    {% if item_count == 0 %}
                                    <span class="total-items">0</span>
                                    {% else %}
                                    {% for item in cart %}
                                    <span class="total-items">{{ item_count }}</span>
                                    {% endfor %}
                                    {% endif %}
                                </a>
                                <!-- Shopping Item -->
                                {% if item_count >= 1 %}
                                <div class="shopping-item">
                                    <div class="dropdown-cart-header">
                                        <span>{{ item_count }}{% if item_count == 1 %}
                                            Item {% else %} Items{% endif %}</span>
                                        <a href="{% url 'cart:cart_detail' %}">View Cart</a>
                                    </div>
                                    <ul class="shopping-list">
                                        {% for item in cart %}
                                        <li>
                                            <a href="{% url 'cart:card_remove' item.product.id %}" class="remove"
                                                title="Remove this item"><i class="lni lni-close"></i></a>
                                            <div class="cart-img-head">
                                                <a class="cart-img"
                                                    href="{% url 'shop:product_detail' item.product.slug %}"><img
                                                        src="{{item.product.image.url}}" alt="#"></a>
                                            </div>

                                            <div class="content">
                                                <h4><a
                                                        href="{% url 'shop:product_detail' item.product.slug %}">{{item.product.name}}</a>
                                                </h4>
                                                <p class="quantity">{{item.quantity}}x - <span
                                                        class="amount">${{item.total_price}}</span></p>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                    <div class="bottom">
                                        <div class="total">
                                            <span>Total</span>
                                            <span class="total-amount">${{cart.get_total_price}}</span>
                                        </div>
                                        <div class="button">
                                            <a href="#" class="btn animate">Checkout</a>
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                                <!--/ End Shopping Item -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Header Middle -->
    <!-- Start Header Bottom -->
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-8 col-md-6 col-12">
                <div class="nav-inner">
                    <!-- Start Mega Category Menu -->
                    <div class="mega-category-menu">
                        <span class="cat-button"><i class="lni lni-menu"></i>All Categories</span>
                        <ul class="sub-category">
                            {% for category in categories %}
                            <li>
                                <a href="{% url 'shop:category_product_list' category.slug %}">{{category.name}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- End Mega Category Menu -->
                    <!-- Start Navbar -->
                    <nav class="navbar navbar-expand-lg">
                        <button class="navbar-toggler mobile-menu-btn" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="toggler-icon"></span>
                            <span class="toggler-icon"></span>
                            <span class="toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
                            <ul id="nav" class="navbar-nav ms-auto">
                                <li class="nav-item">
                                    <a href="{% url 'shop:home' %}" aria-label="Toggle navigation">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dd-menu collapsed" href="javascript:void(0)" data-bs-toggle="collapse"
                                        data-bs-target="#submenu-1-4" aria-controls="navbarSupportedContent"
                                        aria-expanded="false" aria-label="Toggle navigation">Blog</a>
                                    <ul class="sub-menu collapse" id="submenu-1-4">
                                        <li class="nav-item"><a href="{% url 'blog:article_list' %}">All Article</a>
                                        </li>
                                        <hr>
                                        {% for article_cat in article_categories %}
                                        <li class="nav-item"><a href="{% url 'blog:category_article_list' article_cat.slug %}">{{article_cat.title}}</a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            </ul>
                        </div> <!-- navbar collapse -->
                    </nav>
                    <!-- End Navbar -->
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-12">
                <!-- Start Nav Social -->
                <div class="nav-social">
                    <h5 class="title">Follow Us:</h5>
                    <ul>
                        <li>
                            <a href="javascript:void(0)"><i class="lni lni-facebook-filled"></i></a>
                        </li>
                        <li>
                            <a href="javascript:void(0)"><i class="lni lni-twitter-original"></i></a>
                        </li>
                        <li>
                            <a href="javascript:void(0)"><i class="lni lni-instagram"></i></a>
                        </li>
                        <li>
                            <a href="javascript:void(0)"><i class="lni lni-skype"></i></a>
                        </li>
                    </ul>
                </div>
                <!-- End Nav Social -->
            </div>
        </div>
    </div>
    <!-- End Header Bottom -->
</header>

templates/inc/paginator.html
<div class="row">
    <div class="col-12">
        <div class="pagination left">
            {% if page_obj %}
            <ul class="pagination-list">
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}"><i class="lni lni-chevron-left"></i></a>
                </li>
                {% else %}
                <li><a href="javascript:void(0)"><i class="lni lni-chevron-left"></i></a></li>
                {% endif %}
                {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                <li class="active"><a href="javascript:void(0)"><span>{{ i }} </span></a></li>
                {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}"><i class="lni lni-chevron-right"></i></a></li>
                {% else %}
                <li><a href="javascript:void(0)"><i class="lni lni-chevron-right"></i></a></li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>